// React-JS Projects/todos-list/src/MyComponents/AddTodo.js
import React, { useState } from 'react';

export const AddTodo = ({ addTodo }) => {
    const [title, setTitle] = useState("");
    const [desc, setDesc] = useState("");


    const submit = (e) => {
        e.preventDefault();
        if (!title || !desc) {
            alert("Title or Description cannot be blank");
        }
        else {
            addTodo(title, desc);
            setTitle("");
            setDesc("");
        }
    }
    return (
        <div className="container my-3">
            <h3>Add a Todo</h3>
            <form onSubmit={submit}>
                <div className="mb-3">
                    <label htmlFor="title" className="form-label">Todo Title</label>
                    <input type="text" value={title} onChange={(e) => setTitle(e.target.value)} className="form-control" id="title" aria-describedby="emailHelp" />

                </div>
                <div className="mb-3">
                    <label htmlFor="desc" className="form-label">Todo Description</label>
                    <input type="text" value={desc} onChange={(e) => setDesc(e.target.value)} className="form-control" id="desc" />
                </div>
                <button type="submit" className="btn btn-sm btn-success">Add Todo</button>
            </form>
        </div>
    )
}

// AngularJS Projects/todo-list/src/app/MyComponents/add-todo/add-todo.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { Todo } from 'src/app/Todo';

@Component({
  selector: 'app-add-todo',
  templateUrl: './add-todo.component.html',
  styleUrls: ['./add-todo.component.css']
})
export class AddTodoComponent implements OnInit {
  title:string;
  desc:string;
  @Output() todoAdd: EventEmitter<Todo> = new EventEmitter();

  constructor() { }

  ngOnInit(): void {
  }
  onSubmit(){
    const todo = {
      sno: 8,
      title: this.title,
      desc: this.desc,
      active: true
    }
    this.todoAdd.emit(todo);

  }

}

<div class="my-3">
<h4>Add a Todo</h4>
<form (ngSubmit)="onSubmit()">
    <div class="form-group">
      <label for="title">Todo Title</label>
      <input type="text" [(ngModel)]="title" class="form-control" id="title" name="title" aria-describedby="emailHelp"> 
    </div>
    <div class="form-group">
      <label for="desc">Todo Description</label>
      <input type="text" class="form-control" name="desc" id="desc" [(ngModel)]="desc">
    </div> 
    <button type="submit" class="btn btn-sm btn-primary">Add Todo</button>
  </form></div>
